-- Sigmaris self-narrative: weekly growth journal and x_post_history score column.

-- ─── sigmaris_narrative ───────────────────────────────────────────────────────
-- Weekly self-narrative chapters generated by Sigmaris.
-- Service-role-only (no user RLS policies), like sigmaris_self_model.

create table if not exists public.sigmaris_narrative (
  id               uuid        primary key default gen_random_uuid(),
  chapter          integer     not null default 1 check (chapter > 0),
  title            text        not null default '',
  summary          text        not null default '',
  key_events       jsonb       not null default '[]'::jsonb,
  self_reflection  text        not null default '',
  emotional_tone   text        not null default 'growing'
    check (emotional_tone in ('curious', 'growing', 'stable', 'questioning')),
  created_at       timestamptz not null default timezone('utc', now()),
  updated_at       timestamptz not null default timezone('utc', now())
);

create index if not exists idx_sigmaris_narrative_created_at
  on public.sigmaris_narrative (created_at desc);

create index if not exists idx_sigmaris_narrative_chapter
  on public.sigmaris_narrative (chapter desc);

create trigger trg_sigmaris_narrative_updated_at
  before update on public.sigmaris_narrative
  for each row execute function public.set_updated_at();

-- RLS: enable with no user policies → only service_role (bypasses RLS) can access.
alter table public.sigmaris_narrative enable row level security;


-- ─── x_post_history: add post_score + narrative_reflection type ───────────────
-- post_score records the LLM content-audit score (0–10) at post time.
-- narrative_reflection is added as a valid post type.

alter table public.x_post_history
  add column if not exists post_score float;

comment on column public.x_post_history.post_type is
  'memory_gained | research_discovery | self_update | quiet_observation | narrative_reflection';
